micronaut:
  application:
    name: corenew
r2dbc:
  datasources:
    default:
      driver-class-name: org.postgresql.Driver
      schema-generate: CREATE
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5438/postgres
      username: 'postgres'
      password: 'postgres'
netty:
  default:
    allocator:
      max-order: 3