micronaut:
  application:
    name: corenew
  ssl:
    enabled: true
    build-self-signed: true
  server:
    ssl:
      enabled: true
      port: 10030
      build-self-signed: true
    cors:
      enabled: true
  security:
    ip-patterns:
      - 127.0.0.1

r2dbc:
  datasources:
    default:
      driver-class-name: org.postgresql.Driver
      schema-generate: CREATE
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5438/postgres
      username: 'postgres'
      password: 'postgres'
netty:
  default:
    allocator:
      max-order: 3