micronaut:
  application:
    name: corenew
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      db-type: postgres
vertx:
  pg:
    client:
      port: 5432
      host: the-host
      database: the-db
      user: user
      password: password
      maxSize: 5
netty:
  default:
    allocator:
      max-order: 3
jasync:
  client:
    port: 5432
    host: the-host
    database: the-db
    username: test
    password: test
    maxActiveConnections: 5
