micronaut:
  application:
    name: core
  server:
    ssl:
      enabled: true
      port: 10030
      build-self-signed: true
    cors:
      enabled: true
  security:
    redirect:
      enabled: true
    authentication: cookie # <1>
    ip-patterns:
      - 127.0.0.1.*
      - 0:0:0:0:0:0:0:1
    jwt:
      cookie:
        cookie-secure: true
        cookie-same-site: None
      signatures:
        secret:
          generator:
            secret: pleaseChangeThisSecretForANewOneEeEeEeEeEeEe
            base64: true
            jws-algorithm: HS256
      generator:
        refresh-token:
          secret: pleaseChangeThisSecretForANewOneEeEeEeEeEeEe
          base64: true
          jws-algorithm: HS256

r2dbc:
  datasources:
    default:
      database: postgres
      driver-class-name: org.postgresql.Driver
      schema-generate: NONE
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5438/postgres?currentSchema=core
      username: 'postgres'
      password: 'postgres'
netty:
  default:
    allocator:
      max-order: 3